# Generated by Django 5.0 on 2023-12-18 07:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('chatbot', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='imageprofile',
            name='name',
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
    ]
